### ISSUE TITLE
Is it possible to run the node, without running all currency nodes locally (xmr, ltc, btc, etc.)

### ISSUE THREAD

**Issue by SarcasticNoodle** [tecnovert/basicswap#47]
I would like to use remote nodes to remove the need to syncing all chains

**Comment by nahuhh** [comment]
At least for xmr, yes. 
ive not tried with the others chains

**Comment by SarcasticNoodle** [comment]
Ahh thanks, now I found the part in the [manual](https://github.com/tecnovert/basicswap/blob/master/doc/install.md#fastsync), thanks
